services:
  object-detection-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: object-detection-dashboard
    ports:
      - "7070:7070"
    environment:
      - PYTHONPATH=/app
      - KMP_DUPLICATE_LIB_OK=TRUE
    volumes:
      # Mount models directory for easy model updates
      - ./data:/app/data
      - ./yolov8n.pt:/app/yolov8n.pt
      # Mount output directory for saving results
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - detection-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: detection-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - object-detection-dashboard
    restart: unless-stopped
    networks:
      - detection-network
    profiles:
      - production

networks:
  detection-network:
    driver: bridge

volumes:
  output:
    driver: local 